import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding recruiter intelligence database...");

  await prisma.recruiterOutreach.deleteMany();
  await prisma.recruiter.deleteMany();

  const recruiters = [
    // ─────────────────────────────────────────
    // TIER S — MUST CONTACT (VC Talent Partners)
    // These people place CPOs/founders at portfolio co's directly
    // ─────────────────────────────────────────
    {
      name: "Shannon Schiltz",
      title: "Head of Talent",
      firm: "Andreessen Horowitz (a16z)",
      firmType: "vc-talent",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "Co-Founder", "VP Product", "CEO"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["AI", "Fintech", "Consumer", "B2B SaaS", "Crypto"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/shannonschiltz/",
      firmWebsite: "https://jobs.a16z.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Shannon,\n\nI'm a CPO/operator with a track record of scaling AI and fintech products from 0→1 and through Series B+. I've been following a16z's portfolio closely — particularly [specific portfolio company] — and would love to be on your radar for CPO, co-founder, or GM roles at portfolio companies.\n\nKey highlights: [Your top metric]. Happy to send a quick brief if helpful.\n\n[Your name]`,
      insiderNote: "a16z talent places execs at portfolio companies. Focus on AI, fintech, consumer. Lead with operator credentials and specific portfolio company knowledge. Keep it under 5 lines.",
      placedRoles: JSON.stringify(["CPO roles at a16z portfolio", "Co-founder matches", "VP Product at Series A-C"]),
    },
    {
      name: "Jenn Saavedra",
      title: "Chief People Officer",
      firm: "Sequoia Capital",
      firmType: "vc-talent",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "CEO", "Co-Founder", "VP Product", "VP Engineering"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["AI", "Enterprise SaaS", "Consumer", "Infrastructure"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/jennsaavedra/",
      firmWebsite: "https://sequoiacap.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Jenn,\n\nI'm an operator with [X years] scaling product orgs at VC-backed companies — most recently [role] at [company], where [key metric]. I'm actively exploring CPO and co-founder opportunities and would love to be connected to Sequoia portfolio companies where there's a fit.\n\nWould a quick intro call make sense?\n\n[Your name]`,
      insiderNote: "Sequoia talent is highly selective. Lead with exits or elite operator credentials. They care deeply about founder-grade thinking. Reference specific Sequoia companies you admire.",
      placedRoles: JSON.stringify(["C-suite at Sequoia portfolio", "Founding team roles"]),
    },
    {
      name: "Maia Josebachvili",
      title: "Talent Partner",
      firm: "Stripe",
      firmType: "vc-talent",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "GM", "Co-Founder"]),
      stagesFocus: JSON.stringify(["series-b", "growth", "public"]),
      industriesFocus: JSON.stringify(["Fintech", "Payments", "B2B SaaS", "Infrastructure"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/maiajosebachvili/",
      firmWebsite: "https://stripe.com/jobs",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Maia,\n\nI'm a product leader with deep fintech and payments experience — previously [role] at [company]. I'm exploring senior product and GM roles at companies at the intersection of payments and developer tooling, and Stripe is obviously at the top of that list.\n\nWould love to learn about opportunities. [Your name]`,
      insiderNote: "Stripe hires extremely selectively. Fintech/payments background essential. They value operators who can think at both product and business level. Know Stripe Atlas, Connect, Billing deeply.",
      placedRoles: JSON.stringify(["VP Product at Stripe", "GM roles", "Senior IC to leadership"]),
    },
    {
      name: "Talitha Dowd",
      title: "Head of Talent",
      firm: "Accel Partners",
      firmType: "vc-talent",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "Co-Founder", "VP Growth"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b"]),
      industriesFocus: JSON.stringify(["SaaS", "Security", "AI", "Marketplace", "Consumer"]),
      geoFocus: JSON.stringify(["SF", "NYC", "London", "Remote", "Europe"]),
      linkedinUrl: "https://www.linkedin.com/in/talithadowd/",
      firmWebsite: "https://jobs.accel.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Talitha,\n\nI'm an operator actively looking for CPO/co-founder opportunities at Series A-B companies. My background: [headline]. I've been following Accel's portfolio — particularly [company] — and would love to be on your radar.\n\nOpen to a quick call? [Your name]`,
      insiderNote: "Accel covers both US and European portfolio. Good for London/Berlin opportunities too. They appreciate operators with international experience.",
      placedRoles: JSON.stringify(["CPO/VP Product at Accel portfolio", "Founding team", "European expansion roles"]),
    },
    {
      name: "Kerri Sherrick",
      title: "Talent Partner",
      firm: "Bessemer Venture Partners",
      firmType: "vc-talent",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "GM", "CMO"]),
      stagesFocus: JSON.stringify(["series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["Cloud", "SaaS", "Security", "Healthcare", "Consumer"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Boston", "Remote"]),
      linkedinUrl: "https://www.linkedin.com/in/kerrisherrick/",
      firmWebsite: "https://www.bvp.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Kerri,\n\nI'm a product and growth leader with [X years] experience scaling B2B SaaS companies — most recently [role/metric]. I'm targeting CPO and VP Product opportunities at Series B+ companies and would love to be considered for BVP portfolio companies.\n\nHappy to share more context. [Your name]`,
      insiderNote: "BVP focuses on cloud and SaaS. They love operators with strong metrics and board-level communication skills. Reference their Atlas benchmarks to show you understand the space.",
      placedRoles: JSON.stringify(["C-suite at BVP portfolio", "VP roles at cloud companies"]),
    },

    // ─────────────────────────────────────────
    // TIER S — EXEC SEARCH FIRMS (Startup/VC-focused)
    // ─────────────────────────────────────────
    {
      name: "Jonathan Chadwick",
      title: "Managing Director",
      firm: "True Search",
      firmType: "exec-search",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "CEO", "CTO", "Co-Founder", "VP Product", "GM"]),
      stagesFocus: JSON.stringify(["series-a", "series-b", "growth", "public"]),
      industriesFocus: JSON.stringify(["AI", "SaaS", "Fintech", "Consumer", "Healthcare"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/jonathanechadwick/",
      website: "https://www.truesearch.com",
      firmWebsite: "https://www.truesearch.com",
      approachMethod: "email",
      approachScript: `Subject: CPO / Senior Product Leader — [Your Name]\n\nHi Jonathan,\n\nI'm a CPO-level product leader actively exploring my next role. Background: [2-line summary with key metric]. I'm targeting CPO, co-founder, and GM roles at Series A–C AI and fintech companies, remote-first or in SF/NYC.\n\nTrue Search places exactly the kind of roles I'm targeting — would love to connect and share my brief.\n\n[Your name]\n[LinkedIn URL]`,
      insiderNote: "True Search is THE top startup exec search firm. They work retained for top VCs. Getting on their radar early is gold. Send a crisp one-pager with metrics. They place CPOs at unicorns regularly.",
      placedRoles: JSON.stringify(["CPO at unicorns", "CEO at Series B+", "Co-founder matches"]),
    },
    {
      name: "Mike Elek",
      title: "Partner",
      firm: "Riviera Partners",
      firmType: "exec-search",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "VP Engineering", "CTO"]),
      stagesFocus: JSON.stringify(["series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["AI", "SaaS", "Consumer", "B2B"]),
      geoFocus: JSON.stringify(["SF", "Remote", "NYC"]),
      linkedinUrl: "https://www.linkedin.com/in/mikeelek/",
      firmWebsite: "https://rivierapartners.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Mike,\n\nI'm a senior product leader (CPO/VP Product background) actively looking for my next role. Specialties: AI products, PLG, 0→1 and scaling through Series B. [Key metric].\n\nRiviera places exactly the roles I'm targeting — would love to be in your network. [Your name]`,
      insiderNote: "Riviera Partners specialises in product and engineering leadership at VC-backed startups. Very respected in the SF ecosystem. They appreciate operators with both technical and business chops.",
      placedRoles: JSON.stringify(["VP Product at top startups", "CPO at Series B", "CTO/VP Eng"]),
    },
    {
      name: "Jennifer Rettig",
      title: "Managing Director",
      firm: "Daversa Partners",
      firmType: "exec-search",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "CEO", "CMO", "CRO", "VP Product", "Co-Founder"]),
      stagesFocus: JSON.stringify(["series-b", "growth", "pre-ipo", "public"]),
      industriesFocus: JSON.stringify(["SaaS", "Fintech", "AI", "Consumer"]),
      geoFocus: JSON.stringify(["NYC", "SF", "Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/jenniferrettig/",
      firmWebsite: "https://daversa.com",
      approachMethod: "email",
      approachScript: `Subject: Executive Product Leader — [Your Name]\n\nHi Jennifer,\n\nI'm reaching out as I'm actively exploring senior executive opportunities. I'm a CPO-level leader with experience scaling products at [stage/type] companies — [key metric].\n\nDaversa places the kinds of roles I'm targeting (CPO, GM, co-founder). Would love to connect and share a brief.\n\n[Your name]`,
      insiderNote: "Daversa is strong on C-suite placements especially NYSE/NASDAQ-adjacent. Good for growth-stage to pre-IPO. They work with top PE and late-stage VC firms.",
      placedRoles: JSON.stringify(["C-suite at growth/pre-IPO", "CPO placements", "Board roles"]),
    },
    {
      name: "Deb Josephs",
      title: "Partner",
      firm: "ON Search Partners",
      firmType: "exec-search",
      tier: "a",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "VP Growth", "CMO", "GM"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["Consumer", "Marketplace", "Mobile", "AI", "SaaS"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote"]),
      linkedinUrl: "https://www.linkedin.com/in/debjosephs/",
      firmWebsite: "https://www.onsearchpartners.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Deb,\n\nI'm a product leader with [X years] in consumer and marketplace products — [key metric]. Actively looking for CPO/VP Product roles at Series A–C companies.\n\nON Search places exactly these kinds of roles — would love to be on your radar. [Your name]`,
      insiderNote: "ON Search Partners is strong in consumer, marketplace, and mobile. Good relationships with top consumer VCs. They respond well to operators with brand-name company backgrounds.",
      placedRoles: JSON.stringify(["CPO at consumer startups", "VP Product placements"]),
    },
    {
      name: "Katharine Mobley",
      title: "Managing Director",
      firm: "Heidrick & Struggles",
      firmType: "exec-search",
      tier: "a",
      rolesFocus: JSON.stringify(["CEO", "CPO", "CMO", "COO", "Board"]),
      stagesFocus: JSON.stringify(["growth", "public", "pe"]),
      industriesFocus: JSON.stringify(["Technology", "Financial Services", "Healthcare", "Consumer"]),
      geoFocus: JSON.stringify(["Global", "SF", "NYC", "London"]),
      linkedinUrl: "https://www.linkedin.com/in/katharinecmobley/",
      firmWebsite: "https://www.heidrick.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Katharine,\n\nI'm a senior executive (CPO/operator background) with [key credential] exploring my next chapter. My focus: C-level and board-adjacent roles at growth-stage and public tech companies.\n\nHeidrick's tech practice is top-tier — would love to be on your radar. [Your name]`,
      insiderNote: "Heidrick is a global exec search firm — good for late-stage, PE, and public company C-suite. Less startup-focused but great for board, COO, and CEO roles at established tech companies.",
      placedRoles: JSON.stringify(["CEO/COO at public tech", "Board roles", "CPO at PE-backed"]),
    },
    {
      name: "Whitney Herd",
      title: "Partner",
      firm: "Korn Ferry",
      firmType: "exec-search",
      tier: "a",
      rolesFocus: JSON.stringify(["CEO", "CPO", "CMO", "COO", "Board", "CHRO"]),
      stagesFocus: JSON.stringify(["growth", "public", "pe"]),
      industriesFocus: JSON.stringify(["Technology", "Digital", "Consumer", "Financial Services"]),
      geoFocus: JSON.stringify(["Global", "SF", "NYC", "London", "Dubai", "Singapore"]),
      linkedinUrl: "https://www.linkedin.com/company/korn-ferry/",
      firmWebsite: "https://www.kornferry.com",
      approachMethod: "apply-to-firm",
      approachScript: `Visit kornferry.com/candidates and create a profile. Then reach out directly via LinkedIn to their tech practice partners with:\n\n"Hi [Name], I'm a CPO-level executive with [credential] actively exploring C-suite opportunities. I've submitted my profile via your candidate portal and wanted to connect directly. Happy to share a brief. [Your name]"`,
      insiderNote: "Korn Ferry is the world's largest exec search firm. Less startup-focused, better for F500 and PE-backed. Submit to their portal AND connect on LinkedIn. Their tech practice is strong in SF and London.",
      placedRoles: JSON.stringify(["CEO/C-suite at F500", "PE-backed CPO", "Board directors"]),
    },

    // ─────────────────────────────────────────
    // TIER A — BOUTIQUE & SPECIALIST FIRMS
    // ─────────────────────────────────────────
    {
      name: "Ben Braverman",
      title: "Founder & CEO",
      firm: "Flexa",
      firmType: "boutique",
      tier: "a",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "Head of Growth", "GM"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b"]),
      industriesFocus: JSON.stringify(["AI", "SaaS", "Consumer", "Fintech"]),
      geoFocus: JSON.stringify(["Remote", "SF", "NYC"]),
      linkedinUrl: "https://www.linkedin.com/in/benbraverman/",
      firmWebsite: "https://flexa.careers",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Ben,\n\nI'm a product and growth leader (CPO background) actively looking for my next role at a high-growth startup. [Key metric]. Flexible on stage but focused on companies where product is a primary growth lever.\n\nWould love to be in your network. [Your name]`,
      insiderNote: "Flexa specialises in remote-first executive roles. Great for finding remote CPO/VP Product positions. Very active on LinkedIn. Strong AI and SaaS network.",
      placedRoles: JSON.stringify(["Remote-first exec roles", "VP Product", "Head of Growth"]),
    },
    {
      name: "Karen Moroney",
      title: "Head of Executive Search",
      firm: "Spencer Stuart",
      firmType: "exec-search",
      tier: "a",
      rolesFocus: JSON.stringify(["CPO", "CEO", "CMO", "COO", "Board"]),
      stagesFocus: JSON.stringify(["growth", "public", "pe"]),
      industriesFocus: JSON.stringify(["Technology", "Digital Media", "Consumer", "Retail Tech"]),
      geoFocus: JSON.stringify(["Global", "London", "NYC", "SF", "Dubai"]),
      linkedinUrl: "https://www.linkedin.com/company/spencer-stuart/",
      firmWebsite: "https://www.spencerstuart.com",
      approachMethod: "apply-to-firm",
      approachScript: `Visit spencerstuart.com and find their technology practice. Send a LinkedIn message to their tech practice partners:\n\n"Hi [Name], I'm a CPO/operator with [credential] actively exploring C-suite and board opportunities. Would love to be on Spencer Stuart's radar for tech sector mandates. Happy to share my background brief. [Your name]"`,
      insiderNote: "Spencer Stuart is elite for board and C-suite at public/PE companies. Good for London, Dubai, Singapore. They respond to operators with board-ready profiles. Build a relationship before you need them.",
      placedRoles: JSON.stringify(["Board roles", "C-suite at global tech", "CPO at FTSE companies"]),
    },
    {
      name: "Tyler Hogge",
      title: "VP Product",
      firm: "Pelion Venture Partners",
      firmType: "vc-talent",
      tier: "a",
      rolesFocus: JSON.stringify(["VP Product", "CPO", "Co-Founder"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b"]),
      industriesFocus: JSON.stringify(["Fintech", "SaaS", "AI"]),
      geoFocus: JSON.stringify(["Remote", "SF", "NYC", "Salt Lake City"]),
      linkedinUrl: "https://www.linkedin.com/in/tylerhogge/",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Tyler,\n\nI'm a CPO-level product leader exploring my next role. Background: [headline with metric]. I'm focused on Series A-B fintech and SaaS companies and would love to be on Pelion's radar for portfolio opportunities.\n\n[Your name]`,
      insiderNote: "Tyler Hogge is an operator-turned-VC. Very accessible on LinkedIn, writes about product leadership. He responds well to people who engage with his content first.",
      placedRoles: JSON.stringify(["CPO/VP Product at Pelion portfolio"]),
    },
    {
      name: "Lenny Rachitsky",
      title: "Author / Angel Investor",
      firm: "Lenny's Newsletter",
      firmType: "independent",
      tier: "a",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "Head of Product", "Co-Founder"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["Consumer", "SaaS", "AI", "Marketplace"]),
      geoFocus: JSON.stringify(["Remote", "SF", "NYC", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/lennyrachitsky/",
      twitterUrl: "https://twitter.com/lennysan",
      website: "https://www.lennysnewsletter.com",
      approachMethod: "warm-intro",
      approachScript: `DM on Twitter/LinkedIn:\n\n"Hi Lenny, longtime reader — your [specific post] shaped how I think about [topic]. I'm a CPO-level leader with [key credential] exploring my next role. Any chance you'd be open to a quick chat or know of relevant opportunities in your network?\n\n[Your name]"`,
      insiderNote: "Lenny has 800K+ subscribers and an enormous product leader network. Not a recruiter, but a warm referral from him is worth 10 cold applications. Engage with his content first — reply to his posts with genuine insight before reaching out.",
      placedRoles: JSON.stringify(["Informal referrals to top product roles"]),
    },
    {
      name: "Shruti Bhatt",
      title: "Partner, Talent",
      firm: "Lightspeed Venture Partners",
      firmType: "vc-talent",
      tier: "s",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "VP Growth", "GM", "Co-Founder"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["Enterprise SaaS", "AI", "Consumer", "Fintech", "Health"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote", "India", "Global"]),
      linkedinUrl: "https://www.linkedin.com/in/shrutibhatt/",
      firmWebsite: "https://lsvp.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Shruti,\n\nI'm an operator and product leader with [X years] scaling AI and SaaS products — [key metric]. I'm actively exploring CPO, co-founder, and GM roles and would love to be on Lightspeed's radar.\n\nSpecifically excited about your enterprise AI and fintech portfolio. [Your name]`,
      insiderNote: "Lightspeed has strong India + US portfolio. Good for operators with international exposure. They care about founders who can operate globally. Shruti is approachable and responds to genuine messages.",
      placedRoles: JSON.stringify(["CPO/GM at Lightspeed portfolio", "Founding team", "India market roles"]),
    },
    {
      name: "Michelle Labbe",
      title: "Partner",
      firm: "Toptal Executive Network",
      firmType: "boutique",
      tier: "b",
      rolesFocus: JSON.stringify(["Fractional CPO", "Consulting", "Interim GM", "Advisory"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b"]),
      industriesFocus: JSON.stringify(["Tech", "SaaS", "Fintech", "E-commerce"]),
      geoFocus: JSON.stringify(["Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/company/toptal/",
      firmWebsite: "https://www.toptal.com/finance/interim-cfos-and-cpos",
      approachMethod: "apply-to-firm",
      approachScript: `Apply at toptal.com/product/vetting. Then send a message:\n\n"Hi, I'm applying to Toptal's executive network for Fractional CPO and consulting roles. Background: [2-line summary]. I'm focused on AI and fintech companies that need senior product leadership on a flexible engagement basis. [Your name]"`,
      insiderNote: "Toptal is great for fractional CPO work — good for building a consulting track record while you find a full-time role. Also pays very well ($200-400/hr for senior execs). Vetting process is rigorous but worth it.",
      placedRoles: JSON.stringify(["Fractional CPO", "Consulting engagements", "Interim executive"]),
    },
    {
      name: "Todd Goldberg",
      title: "Partner",
      firm: "Emergence Capital",
      firmType: "vc-talent",
      tier: "a",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "Co-Founder", "CEO"]),
      stagesFocus: JSON.stringify(["series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["Enterprise SaaS", "AI", "Cloud", "Future of Work"]),
      geoFocus: JSON.stringify(["SF", "Remote", "NYC"]),
      linkedinUrl: "https://www.linkedin.com/in/toddgoldberg/",
      firmWebsite: "https://www.emcap.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Todd,\n\nI'm a product and growth leader with deep enterprise SaaS experience — [key metric]. I'm actively exploring CPO and co-founder opportunities at enterprise AI companies and would love to be on Emergence's radar.\n\nYour portfolio companies like [specific company] are exactly the kind of stage and problem space I'm excited about. [Your name]`,
      insiderNote: "Emergence Capital focuses exclusively on enterprise SaaS. If you have enterprise B2B experience, this is a top contact. Todd is an operator-turned-VC and very accessible.",
      placedRoles: JSON.stringify(["CPO/VP Product at enterprise SaaS", "Founding team"]),
    },
    {
      name: "Aishwarya Iyer",
      title: "Talent Partner",
      firm: "General Catalyst",
      firmType: "vc-talent",
      tier: "a",
      rolesFocus: JSON.stringify(["CPO", "VP Product", "Co-Founder", "GM", "VP Growth"]),
      stagesFocus: JSON.stringify(["seed", "series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["AI", "Climate Tech", "Healthcare", "Consumer", "SaaS"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Boston", "Remote", "Global"]),
      linkedinUrl: "https://www.linkedin.com/company/general-catalyst-partners/",
      firmWebsite: "https://www.generalcatalyst.com",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Aishwarya,\n\nI'm an operator with [X years] experience and [key metric]. I'm actively looking for CPO and co-founder roles and am particularly excited about General Catalyst's AI and climate tech portfolio.\n\nWould love to be on your radar for portfolio company opportunities. [Your name]`,
      insiderNote: "General Catalyst is very active in AI and climate tech. They appreciate operators with mission-driven backgrounds. Good for NYC-based or Boston roles. Very responsive talent team.",
      placedRoles: JSON.stringify(["C-suite at GC portfolio", "Founding team matches"]),
    },

    // ─────────────────────────────────────────
    // TIER B — INDEPENDENT & NICHE
    // ─────────────────────────────────────────
    {
      name: "Britt Flaherty",
      title: "Executive Recruiter",
      firm: "Independent / Product Leadership",
      firmType: "independent",
      tier: "b",
      rolesFocus: JSON.stringify(["VP Product", "CPO", "Head of Product", "Director of Product"]),
      stagesFocus: JSON.stringify(["series-a", "series-b", "growth"]),
      industriesFocus: JSON.stringify(["Consumer Tech", "Mobile", "Marketplace", "SaaS"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote"]),
      linkedinUrl: "https://www.linkedin.com/in/brittflaherty/",
      approachMethod: "linkedin-dm",
      approachScript: `Hi Britt,\n\nI'm a product leader actively exploring senior IC and leadership roles. Background: [headline with metric]. Would love to be in your network for CPO/VP Product opportunities.\n\n[Your name]`,
      insiderNote: "Independent recruiter focused on product leadership. Good for VP Product and Director-level roles. Very active on LinkedIn job posts.",
      placedRoles: JSON.stringify(["VP Product", "Senior PM", "Head of Product"]),
    },
    {
      name: "Nikhil Basu Trivedi",
      title: "Partner",
      firm: "Footwork VC",
      firmType: "vc-talent",
      tier: "b",
      rolesFocus: JSON.stringify(["Co-Founder", "CPO", "VP Product"]),
      stagesFocus: JSON.stringify(["seed", "series-a"]),
      industriesFocus: JSON.stringify(["Consumer", "Marketplace", "Mobile", "Social"]),
      geoFocus: JSON.stringify(["SF", "NYC", "Remote"]),
      linkedinUrl: "https://www.linkedin.com/in/nikhilbasutrivedi/",
      twitterUrl: "https://twitter.com/nbt",
      approachMethod: "warm-intro",
      approachScript: `Twitter/LinkedIn DM:\n\n"Hi Nikhil, big fan of your writing on [topic]. I'm an operator with [credential] exploring co-founder and CPO opportunities — specifically in consumer and marketplace. Any chance you have portfolio companies where there might be a fit? [Your name]"`,
      insiderNote: "Nikhil is very active on Twitter. Engage with his content before reaching out. Good for consumer and marketplace seed/Series A. He responds to operators with consumer product experience.",
      placedRoles: JSON.stringify(["Co-founder matches", "Seed-stage CPO"]),
    },
  ];

  for (const r of recruiters) {
    await prisma.recruiter.create({ data: r });
  }

  console.log(`✅ Seeded ${recruiters.length} recruiters across all tiers`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
